import express from "express";
import { signup, login, logout, checkAuth } from "../controllers/authController.js";
import { protectRoute } from "../middleware/protectedRoute.js";
import { loginLimiter, signupLimiter } from "../middleware/rateLimiter.js";
const router = express.Router();
router.post("/signup", signupLimiter, signup);
router.post("/login", loginLimiter, login);
router.post("/logout", logout);
router.get("/checkAuth", protectRoute, checkAuth);
export default router;