import express from "express";
import { signup, login, logout, checkAuth, updateProfile } from "../controllers/authController.js";
import { protectRoute } from "../middleware/protectedRoute.js";
import { arcjetProtection } from "../middleware/arcjetMiddlware.js";
const router = express.Router();
router.use(arcjetProtection);
router.post("/signup", signup);
router.post("/login", login);
router.post("/logout", logout);
router.get("/checkAuth", protectRoute, checkAuth);
router.put("/update-profile", protectRoute, updateProfile);
export default router;